### PR TITLE
Proofreading 2

### PR DESCRIPTION
**Pull request by embray**

### CODE REVIEW

**Comment by minrk** [comment]
In under the wire!

**Comment by minrk** [comment]
Submitting with these revisions now

**Comment by embray** [comment]
I'll keep adding more as I find them, but obviously it will be too late for submission at this point :)

**Comment by nthiery** [comment]
>    I'll keep adding more as I find them, but obviously it will be too late
>    for submission at this point :)

The document will be useful throughout the lifetime of the project, so
that's useful in any case!

**Pull request merged**
