### PR TITLE
Remove objectives detailed description

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by nthiery** [comment]
I agree that the current description was too technical and will fit better in the work package.

In fact, the objective formulation itself is kind of technical: Rather than revolving around the software solution (Jupyter widgets) it could revolve around the user experience (e.g. improved real-time interactivity in Jupyter; export/rendering of notebooks on the web, ...).

**Comment by nthiery** [comment]
More general question: do we want to have detailed objective descriptions like we had in ODK's proposal?

**Comment by SylvainCorlay** [comment]
Since I am the only one to have added a detailed description, I thought it was unnecessary

**Comment by nthiery** [comment]
> Since I am the only one to have added a detailed description, I thought it was unnecessary

Which is fair enough! My question is indeed about all the other objectives (so not really in-scope to that PR, which I think we can merge as is)
@minrk , @fangohr: what do you think?

**Comment by minrk** [comment]
Yeah, we can take a pass on the objectives to make them more clearly focused on user/social results rather than technical

**Pull request merged**
